import type { CatalogSection } from "./types";

export const sortingCatalog: CatalogSection = {
    title: "Sorting",
  description: "Compare, swap, partition, and merge array-based ordering algorithms.",
    entries: [
      { title: "Bubble Sort", tag: "O(n²)", status: "playable", kind: "sort", id: "bubble" },
      { title: "Insertion Sort", tag: "O(n²), adaptive", status: "playable", kind: "sort", id: "insertion" },
      { title: "Selection Sort", tag: "O(n²)", status: "playable", kind: "sort", id: "selection" },
      { title: "Merge Sort", tag: "O(n log n)", status: "playable", kind: "sort", id: "merge" },
      { title: "Quick Sort", tag: "O(n log n) avg", status: "playable", kind: "sort", id: "quick" },
      { title: "Heap Sort", tag: "O(n log n)", status: "playable", kind: "sort", id: "heap" },
      { title: "Counting Sort", tag: "O(n + k)", status: "playable", kind: "sort", id: "counting" },
      { title: "Radix Sort", tag: "O(d(n + k))", status: "playable", kind: "sort", id: "radix" },
      { title: "Bucket Sort", tag: "O(n + k) avg", status: "playable", kind: "sort", id: "bucket" },
      { title: "Shell Sort", tag: "Gap based", status: "playable", kind: "sort", id: "shell" },
      { title: "TimSort", tag: "O(n log n)", status: "playable", kind: "sort", id: "tim" },
      { title: "IntroSort", tag: "O(n log n)", status: "playable", kind: "sort", id: "intro" },
      { title: "Cycle Sort", tag: "O(n²)", status: "playable", kind: "sort", id: "cycle" },
      { title: "Cocktail Sort", tag: "O(n²)", status: "playable", kind: "sort", id: "cocktail" },
      { title: "Comb Sort", tag: "O(n²)", status: "playable", kind: "sort", id: "comb" },
      { title: "Pigeonhole Sort", tag: "O(n + range)", status: "playable", kind: "sort", id: "pigeonhole" },
      { title: "Bead Sort", tag: "Specialized", status: "playable", kind: "sort", id: "bead" },
      { title: "Pancake Sort", tag: "O(n²)", status: "playable", kind: "sort", id: "pancake" },
      { title: "Exchange Sort", tag: "O(n²)", status: "playable", kind: "sort", id: "exchange" },
      { title: "Gnome Sort", tag: "O(n²)", status: "playable", kind: "sort", id: "gnome" },
      { title: "Odd-Even Sort", tag: "O(n²)", status: "playable", kind: "sort", id: "oddEven" },
      { title: "Binary Insertion Sort", tag: "O(n²)", status: "playable", kind: "sort", id: "binaryInsertion" },
      { title: "Stooge Sort", tag: "O(n^2.7)", status: "playable", kind: "sort", id: "stooge" },
      { title: "Bogo Sort", tag: "Unbounded", status: "playable", kind: "sort", id: "bogo" },
      { title: "Strand Sort", tag: "O(n²)", status: "playable", kind: "sort", id: "strand" },
      { title: "Bitonic Sort", tag: "O(log² n)", status: "playable", kind: "sort", id: "bitonic" },
      { title: "Smoothsort", tag: "O(n log n)", status: "playable", kind: "sort", id: "smooth" },
    ],
  };
