name: Bug report
description: Report a bug
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: textarea
    id: bug
    attributes:
      label: Bug description
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
